Problem Statement 2:
A dataset collected in a cosmetics shop showing details of customers and whether or not they responded to a special offer to buy a new lipstick is shown in the table below. Use this dataset to build a decision tree, with Buys as the target variable, to help in buying lip-sticks in the future. Find the root node of the decision tree. According to the decision tree, you have made from the previous Training data set, what is the decision for the test data: [Age < 21, Income = Low, Gender = Female, Marital Status = Married]? Write the concluding statement for the implemented application.


```
# This is formatted as code
```



In [105]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import log2 as log

In [106]:
eps = np.finfo(float).eps

In [107]:
dataset2 ={
    'id':[1,2,3,4,5,6,7,8,9,10,11,12,13,14],
    'age':['<21','<21','21-35','>35','>35','>35','21-35','<21','<21','>35','<21','21-35','21-35','>35'],
    'income':['high','high','high','medium','low','low','low','medium','low','medium','medium','medium','high','medium'],
    'gender':['male','male','male','male','female','female','female','male','female','female','female','male','female','male'],
    'marital status':['single','married','single','single','single','married','married','single','married','single','married','married','single','married'],
    'buys':['no','no','yes','yes','yes','no','yes','no','yes','yes','yes','yes','yes','no'],
    
}

In [108]:
#extra dataframe to compare labels
df2=pd.DataFrame(dataset2,columns=['id','age','income','gender','marital status','buys'])

In [109]:
df=pd.DataFrame(dataset2,columns=['id','age','income','gender','marital status','buys'])

In [110]:
df=df.drop('id',axis=1)

In [111]:
df

age  income  gender marital status buys
0     <21    high    male         single   no
1     <21    high    male        married   no
2   21-35    high    male         single  yes
3     >35  medium    male         single  yes
4     >35     low  female         single  yes
5     >35     low  female        married   no
6   21-35     low  female        married  yes
7     <21  medium    male         single   no
8     <21     low  female        married  yes
9     >35  medium  female         single  yes
10    <21  medium  female        married  yes
11  21-35  medium    male        married  yes
12  21-35    high  female         single  yes
13    >35  medium    male        married   no

In [112]:
df.buys.value_counts()

yes    9
no     5
Name: buys, dtype: int64

In [113]:
df.shape

(14, 5)

In [114]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [115]:
x

array([['<21', 'high', 'male', 'single'],
       ['<21', 'high', 'male', 'married'],
       ['21-35', 'high', 'male', 'single'],
       ['>35', 'medium', 'male', 'single'],
       ['>35', 'low', 'female', 'single'],
       ['>35', 'low', 'female', 'married'],
       ['21-35', 'low', 'female', 'married'],
       ['<21', 'medium', 'male', 'single'],
       ['<21', 'low', 'female', 'married'],
       ['>35', 'medium', 'female', 'single'],
       ['<21', 'medium', 'female', 'married'],
       ['21-35', 'medium', 'male', 'married'],
       ['21-35', 'high', 'female', 'single'],
       ['>35', 'medium', 'male', 'married']], dtype=object)

In [116]:
y

array(['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no'], dtype=object)

In [117]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
x[:,0]=le.fit_transform(x[:,0])
x[:,1]=le.fit_transform(x[:,1])
x[:,2]=le.fit_transform(x[:,2])
x[:,3]=le.fit_transform(x[:,3])

In [118]:
df

age income gender marital status buys
0    1      0      1              1   no
1    1      0      1              0   no
2    0      0      1              1  yes
3    2      2      1              1  yes
4    2      1      0              1  yes
5    2      1      0              0   no
6    0      1      0              0  yes
7    1      2      1              1   no
8    1      1      0              0  yes
9    2      2      0              1  yes
10   1      2      0              0  yes
11   0      2      1              0  yes
12   0      0      0              1  yes
13   2      2      1              0   no

In [119]:
y=label.fit_transform(y)

In [120]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [121]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)
x_train

array([[2, 2, 1, 0],
       [2, 2, 0, 1],
       [1, 0, 1, 0],
       [1, 2, 1, 1],
       [1, 2, 0, 0],
       [2, 2, 1, 1],
       [1, 0, 1, 1],
       [2, 1, 0, 0],
       [0, 0, 0, 1]], dtype=object)

In [122]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 0, 1])

In [123]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [124]:

prediction = dt.predict([[1,1,0,0]])
prediction

array([1])